# Generated by Django 3.2.9 on 2021-11-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='NameOfTeacher',
            new_name='name_of_teacher',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='NumberOfLesson',
            new_name='number_of_lesson',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='FullName',
            new_name='full_name',
        ),
    ]
