# Generated by Django 3.2.9 on 2021-11-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20211112_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='users_name',
        ),
    ]
