# Generated by Django 3.2.9 on 2021-11-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_customuser_users_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
